# Generated by Django 4.0 on 2023-05-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='discription',
            new_name='description',
        ),
    ]
