# Generated by Django 4.0 on 2023-05-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_id',
        ),
    ]
