# Generated by Django 4.0 on 2023-06-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_article_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_id',
        ),
    ]
