# Generated by Django 4.0 on 2023-06-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_article_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='userid',
        ),
    ]
