# Generated by Django 4.0 on 2023-06-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_user_id_article_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.CharField(default='today', max_length=50),
        ),
    ]
