# Generated by Django 4.0 on 2023-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.CharField(default='today', max_length=50)),
                ('userid', models.CharField(default='today', max_length=50)),
                ('comment', models.TextField(default='write your comments')),
                ('date', models.CharField(default='today', max_length=50)),
            ],
        ),
    ]
