# Generated by Django 4.0 on 2023-06-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_article_date_alter_comments_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='description',
        ),
    ]
