# Generated by Django 4.0 on 2023-06-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_comment_comments_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articleid',
            field=models.IntegerField(default=34),
        ),
    ]
