# Generated by Django 4.0 on 2023-06-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_comments_articleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articleid',
            field=models.CharField(default='today', max_length=50),
        ),
    ]
