# Generated by Django 4.0 on 2023-06-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_comments_articleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articleid',
            field=models.IntegerField(default=34),
        ),
    ]
