# Generated by Django 4.0 on 2023-06-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_article_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(default=0)),
                ('userid', models.CharField(default='today', max_length=50)),
                ('comments', models.TextField()),
                ('date', models.CharField(default='today', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
