# Generated by Django 4.0 on 2023-06-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_commenting_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenting',
            name='comments',
            field=models.TextField(default='enter comment'),
        ),
    ]
